# Generated by Django 2.1.5 on 2019-01-24 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='start')),
                ('end_time', models.DateTimeField(null=True, verbose_name='end')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.Car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('car', 'start_time', 'end_time')},
        ),
    ]
