# Generated by Django 2.1.5 on 2019-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0002_auto_20190124_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
