# Generated by Django 2.1.5 on 2019-01-24 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbooking', '0003_auto_20190124_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('driver', 'car', 'start_time', 'end_time')},
        ),
    ]
