# Generated by Django 2.1.5 on 2019-01-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0005_auto_20190124_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='start time'),
        ),
    ]
